# This file was generated by GoReleaser. DO NOT EDIT.
cask "hadron" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "da4bad2c1f0867b833a2fcd7023b5d38eb4b8bf9acc1856715aa09e8e693c124"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eeb4785aa7681b50c81668d30b4d002cf9aa83f5664278b1f3a373dfc7766644"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21cce416e8af265972264ff38a0b439a52fd3f6dfaef233c3f17e715321c158a"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "38f6d858f7b54ac95ac74df3cccad2a1b489db1f6cdb642573b70ea1662263b3"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hadron"
  desc "CLI for the Hadron AI-memory platform"
  homepage "https://hadronmemory.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hadron"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hadron"], must_succeed: false
  end

  # No zap stanza required

end
