# This file was generated by GoReleaser. DO NOT EDIT.
cask "hadron" do
  version "0.16.0"

  on_macos do
    on_arm do
      sha256 "cf3e15d34bdee22aa3841b8d3ecab0a277e2b46e6f3c459c5d0ddcb2b5fd8b31"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38e413813d32150f6506fe0adb90cdf5da5f2cf57a378d538b0608b7d4b0f94e"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d6ef39e032669cf048f5d4c9cf2f0aa82b125bef444276cbf723ba892a5c3ebc"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad3a64fbd254ba303b140496cdd0f17abc67ce06f6fab26fb5cd4699d779e3ad"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hadron"
  desc "CLI for the Hadron AI-memory platform"
  homepage "https://hadronmemory.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hadron"

  # No zap stanza required
end
