# This file was generated by GoReleaser. DO NOT EDIT.
cask "hadron" do
  version "0.18.1"

  on_macos do
    on_arm do
      sha256 "40df60a3457ed18d9c7bdef9539b6e29e1702baae71d543c3a0d02a46986afc8"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6b1a167ae03d04e1277b26951ce627e742f7199619fa2c6b506ac3268799cacd"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b8f300f0dd7ca5683465ab59e2a9df915be72ade2a0d6dff432c2bc1ff11cb97"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e78f16345bd935482b752a9205839ebfd5b4e4226b4fc1b8d6d01bd1caf0ac32"
      url "https://github.com/hadron-memory/hadron-cli/releases/download/v#{version}/hadron_#{version}_linux_amd64.tar.gz"
    end
  end

  name "hadron"
  desc "CLI for the Hadron AI-memory platform"
  homepage "https://hadronmemory.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hadron"

  # No zap stanza required
end
